services:
  nginx:
    container_name: nginx-fib
    image: nginx:1.24
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 8611:8000
  backend:
    container_name: backend-fib
    init: true
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ./node/src:/node/src